spring.application.name=banking-core
spring.jpa.hibernate.ddl-auto=validate

server.port=4712

# TEST (Postgres lokal)
#spring.datasource.url=jdbc:postgresql://localhost:5432/banking-test
#spring.datasource.username=postgres
#spring.datasource.password=pgvedder
#spring.datasource.driver.class=org.postgresql.Driver

# PROD (Postgres lokal)
#spring.datasource.url=jdbc:postgresql://localhost:5432/banking-prod
#spring.datasource.username=postgres
#spring.datasource.password=pgvedder
#spring.datasource.driver.class=org.postgresql.Driver

# H2 (mauelle Tests)
spring.datasource.url=jdbc:h2:mem:testdb-h2;INIT=RUNSCRIPT FROM 'classpath:init_h2.sql'
spring.datasource.driver.class=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect