spring.application.name=banking-core
spring.jpa.hibernate.ddl-auto=validate

# PROD
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=banking-db-prod;encrypt=true;trustServerCertificate=true
#spring.datasource.username=banking-db-prod
#spring.datasource.password=banking-db-prod
#spring.datasource.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver

# TEST
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=banking-db-test;encrypt=true;trustServerCertificate=true
#spring.datasource.username=banking-db-test
#spring.datasource.password=banking-db-test
#spring.datasource.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=pgvedder
spring.datasource.driver.class=org.postgresql.Driver


import.rootdir=C:\\tmp\\bankingimportroot